/**
 * openclew index — regenerate doc/_INDEX.md
 *
 * Pure JS implementation. Reuses parsers from search.js (SSOT).
 * Zero dependencies — Node 16+ standard library only.
 */

const fs = require("fs");
const path = require("path");
const { collectDocs } = require("./search");

/**
 * Generate _INDEX.md content from parsed docs.
 *
 * @param {string} docDir - Absolute path to doc/ directory
 * @returns {string} Generated index content
 */
function generateIndex(docDir) {
  const docs = collectDocs(docDir);
  const refdocs = docs.filter((d) => d.kind === "refdoc");
  const logs = docs.filter((d) => d.kind === "log");

  const now = new Date();
  const timestamp = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")} ${String(now.getHours()).padStart(2, "0")}:${String(now.getMinutes()).padStart(2, "0")}`;

  const lines = [
    "# Project Knowledge Index",
    "",
    `> Auto-generated by [openclew](https://github.com/openclew/openclew) on ${timestamp}.`,
    "> Do not edit manually — rebuilt from L1 metadata on every commit.",
    "",
  ];

  // Refdocs section
  lines.push("## Refdocs");
  lines.push("");
  if (refdocs.length) {
    lines.push("| Document | Subject | Status | Category |");
    lines.push("|----------|---------|--------|----------|");
    for (const doc of refdocs) {
      const name = path.basename(doc.filepath);
      const subject = doc.meta.subject || "—";
      const status = doc.meta.status || "—";
      const category = doc.meta.category || "—";
      const relPath = path.relative(path.dirname(docDir), doc.filepath);
      lines.push(`| [${name}](${relPath}) | ${subject} | ${status} | ${category} |`);
    }
  } else {
    lines.push("_No refdocs yet. Create one with `npx openclew add ref \"Title\"`._");
  }
  lines.push("");

  // Logs section (last 20)
  const displayLogs = logs.slice(0, 20);
  lines.push("## Recent logs");
  lines.push("");
  if (displayLogs.length) {
    lines.push("| Date | Subject | Status | Category |");
    lines.push("|------|---------|--------|----------|");
    for (const doc of displayLogs) {
      const date = doc.meta.date || path.basename(doc.filepath).slice(0, 10);
      const subject = doc.meta.subject || "—";
      const status = doc.meta.status || "—";
      const category = doc.meta.category || "—";
      const relPath = path.relative(path.dirname(docDir), doc.filepath);
      lines.push(`| ${date} | [${subject}](${relPath}) | ${status} | ${category} |`);
    }
    if (logs.length > 20) {
      lines.push("");
      lines.push(`_${logs.length - 20} older logs not shown._`);
    }
  } else {
    lines.push("_No logs yet. Create one with `npx openclew add log \"Title\"`._");
  }
  lines.push("");

  // Stats
  lines.push("---");
  lines.push(`**${refdocs.length}** refdocs, **${logs.length}** logs.`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Write _INDEX.md to disk.
 *
 * @param {string} docDir - Absolute path to doc/ directory
 * @returns {{ refdocs: number, logs: number }} Counts
 */
function writeIndex(docDir) {
  const content = generateIndex(docDir);
  const indexPath = path.join(docDir, "_INDEX.md");
  fs.writeFileSync(indexPath, content, "utf-8");

  const docs = collectDocs(docDir);
  const refdocs = docs.filter((d) => d.kind === "refdoc").length;
  const logs = docs.filter((d) => d.kind === "log").length;
  return { refdocs, logs };
}

// CLI runner
function run() {
  const args = process.argv.slice(2);
  const cmdIndex = args.indexOf("index");
  const pathArg = cmdIndex >= 0 ? args[cmdIndex + 1] : args[0];
  const docDir = pathArg && !pathArg.startsWith("-") ? pathArg : path.join(process.cwd(), "doc");

  if (!fs.existsSync(docDir)) {
    console.error("No doc/ directory found. Run 'openclew init' first.");
    process.exit(1);
  }

  const { refdocs, logs } = writeIndex(docDir);
  console.log(`Generated doc/_INDEX.md (${refdocs} refdocs, ${logs} logs)`);
}

if (require.main === module || process.argv.includes("index")) {
  run();
}

module.exports = { generateIndex, writeIndex };
