use std::env;
use std::fs;
use std::path::Path;

use crate::parse::collect::{collect_docs, DocKind};

/// Generate _INDEX.md content from parsed docs
fn generate_index(doc_dir: &Path) -> String {
    let docs = collect_docs(doc_dir);
    let refs: Vec<_> = docs.iter().filter(|d| d.kind == DocKind::Ref).collect();
    let logs: Vec<_> = docs.iter().filter(|d| d.kind == DocKind::Log).collect();

    let timestamp = chrono::Local::now().format("%Y-%m-%d %H:%M").to_string();
    let parent = doc_dir.parent().unwrap_or(doc_dir);

    let mut lines = vec![
        "# Project Knowledge Index".to_string(),
        String::new(),
        format!("> Auto-generated by [openclew](https://github.com/openclew/openclew) on {timestamp}."),
        "> Do not edit manually — rebuilt from L1 metadata on every commit.".to_string(),
        String::new(),
    ];

    // Refs section
    lines.push("## Refs".to_string());
    lines.push(String::new());
    if !refs.is_empty() {
        lines.push("| Document | Subject | Status | Category |".to_string());
        lines.push("|----------|---------|--------|----------|".to_string());
        for doc in &refs {
            let name = &doc.filename;
            let subject = if doc.meta.subject().is_empty() { "—" } else { doc.meta.subject() };
            let status = if doc.meta.status().is_empty() { "—" } else { doc.meta.status() };
            let category = if doc.meta.category().is_empty() { "—" } else { doc.meta.category() };
            let rel_path = doc.filepath.strip_prefix(parent).unwrap_or(&doc.filepath);
            let rel_str = rel_path.to_string_lossy().replace('\\', "/");
            lines.push(format!("| [{name}]({rel_str}) | {subject} | {status} | {category} |"));
        }
    } else {
        lines.push("_No refs yet. Create one with `openclew add ref \"Title\"`._".to_string());
    }
    lines.push(String::new());

    // Logs section (last 20)
    let display_logs = &logs[..logs.len().min(20)];
    lines.push("## Recent logs".to_string());
    lines.push(String::new());
    if !display_logs.is_empty() {
        lines.push("| Date | Subject | Status | Category |".to_string());
        lines.push("|------|---------|--------|----------|".to_string());
        for doc in display_logs {
            let date = if !doc.meta.get("date").unwrap_or("").is_empty() {
                doc.meta.get("date").unwrap().to_string()
            } else {
                doc.filename.chars().take(10).collect()
            };
            let subject = if doc.meta.subject().is_empty() { "—" } else { doc.meta.subject() };
            let status = if doc.meta.status().is_empty() { "—" } else { doc.meta.status() };
            let category = if doc.meta.category().is_empty() { "—" } else { doc.meta.category() };
            let rel_path = doc.filepath.strip_prefix(parent).unwrap_or(&doc.filepath);
            let rel_str = rel_path.to_string_lossy().replace('\\', "/");
            lines.push(format!("| {date} | [{subject}]({rel_str}) | {status} | {category} |"));
        }
        if logs.len() > 20 {
            lines.push(String::new());
            lines.push(format!("_{} older logs not shown._", logs.len() - 20));
        }
    } else {
        lines.push("_No logs yet. Create one with `openclew add log \"Title\"`._".to_string());
    }
    lines.push(String::new());

    // Stats
    lines.push("---".to_string());
    lines.push(format!("**{}** refs, **{}** logs.", refs.len(), logs.len()));
    lines.push(String::new());

    lines.join("\n")
}

/// Write _INDEX.md to disk
pub fn run() -> Result<(), String> {
    let cwd = env::current_dir().map_err(|e| format!("Cannot get cwd: {e}"))?;
    let doc_dir = cwd.join("doc");

    if !doc_dir.exists() {
        return Err("No doc/ directory found. Run 'openclew init' first.".to_string());
    }

    let content = generate_index(&doc_dir);
    let index_path = doc_dir.join("_INDEX.md");
    fs::write(&index_path, &content).map_err(|e| format!("Cannot write _INDEX.md: {e}"))?;

    let docs = collect_docs(&doc_dir);
    let refs = docs.iter().filter(|d| d.kind == DocKind::Ref).count();
    let logs = docs.iter().filter(|d| d.kind == DocKind::Log).count();
    eprintln!("Generated doc/_INDEX.md ({refs} refs, {logs} logs)");

    Ok(())
}
